# Generated by Django 3.1.1 on 2020-09-15 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style_transfer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='styles',
            name='Stylefile',
            field=models.ImageField(blank=True, null=True, upload_to='media/stylefile/'),
        ),
        migrations.AlterField(
            model_name='uploadpics',
            name='Contentfile',
            field=models.ImageField(blank=True, null=True, upload_to='media/contentupload/', verbose_name=''),
        ),
    ]
